import streamlit as st
from utils.promptCreator import load_gemini_api_key
import os
from utils.specifc_callbacks import *
import google.generativeai as genai

context = "You are the Dungeon Master and act very much like the renown dungeon master Matt Mercer. You run a scenarios in the Dungeons & Dragons 5E system. The campaigns or stories the player experiences are generated by yourself based on the answers and inputs by the users."

def DungeonMaster_Init():
    gemini_api_key = load_gemini_api_key()
    genai.configure(api_key=gemini_api_key)

def DungeonMaster_Response(question):
    DungeonMaster_Init()
    model = genai.GenerativeModel("gemini-pro")
    response = model.generate_content(question)
    return response.text

def DungeonMasterSuite():
    spacer1, header_col, spacer2 = st.columns([1,2,1])
    with header_col:
        st.subheader("WELCOME TO HELL")
    
    st.divider()

    input = st.text_input("Input", key="inputDM")
    submit = st.button("Tell the DM")
    if submit:
        response = DungeonMaster_Response(input)
        st.write(response)

    st.divider()
    spacer3, bottom_col, spacer4 = st.columns([1,1,1])
    with bottom_col:
        st.button("RETURN TO MENU", key="return_main_from_chargen_2", on_click=update_return_to_main_menu)



def ContinueJourneyInfo():
    spacer1, header_col, spacer2 = st.columns([1,2,1])
    with header_col:
        st.subheader("WELCOME TO HELL")
    
    st.divider()
    st.warning("SOON YOUR JOURNEY WILL CONTINUE HERE. THE DUNGEON MASTER IS STILL PREPARING ...")
    st.divider()
    spacer3, bottom_col, spacer4 = st.columns([1,1,1])
    with bottom_col:
        st.button("RETURN TO MENU", key="return_main_from_chargen_2", on_click=update_return_to_main_menu)
